"""added Series table changed Game table

Revision ID: 00b1d62cd842
Revises: 
Create Date: 2026-05-07 13:35:40.512018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b1d62cd842'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_date'), ['date'], unique=True)

    op.create_table('splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_splits_layout'), ['layout'], unique=True)
        batch_op.create_index(batch_op.f('ix_splits_value'), ['value'], unique=False)

    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('form_state', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'game_number')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_series_id'), ['series_id'], unique=False)

    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('bowler_name', sa.String(length=64), nullable=False),
    sa.Column('frames', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_series_id'))

    op.drop_table('game')
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_splits_value'))
        batch_op.drop_index(batch_op.f('ix_splits_layout'))

    op.drop_table('splits')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_date'))

    op.drop_table('series')
    # ### end Alembic commands ###
