"""fresh start

Revision ID: 79564707fae9
Revises: 
Create Date: 2026-05-06 12:55:47.346056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79564707fae9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_date'), ['date'], unique=True)

    op.create_table('splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_splits_layout'), ['layout'], unique=True)
        batch_op.create_index(batch_op.f('ix_splits_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_splits_value'))
        batch_op.drop_index(batch_op.f('ix_splits_layout'))

    op.drop_table('splits')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_date'))

    op.drop_table('game')
    # ### end Alembic commands ###
