"""fresh start again

Revision ID: 8d8f5c3218b3
Revises: 
Create Date: 2026-05-06 17:39:37.244942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8f5c3218b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('form_state', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_date'), ['date'], unique=True)

    op.create_table('splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_splits_layout'), ['layout'], unique=True)
        batch_op.create_index(batch_op.f('ix_splits_value'), ['value'], unique=False)

    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('bowler_name', sa.String(length=64), nullable=False),
    sa.Column('frames', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_splits_value'))
        batch_op.drop_index(batch_op.f('ix_splits_layout'))

    op.drop_table('splits')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_date'))

    op.drop_table('game')
    # ### end Alembic commands ###
