"""betting table

Revision ID: 931afa033f4f
Revises: 
Create Date: 2026-04-30 18:13:38.432724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931afa033f4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betting_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('betting_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_betting_page_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betting_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_betting_page_date'))

    op.drop_table('betting_page')
    # ### end Alembic commands ###
