"""change splits amout to splits value

Revision ID: 9437a5ee5b73
Revises: aac9548d365c
Create Date: 2026-04-30 20:06:04.038190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9437a5ee5b73'
down_revision = 'aac9548d365c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_splits_amount'))
        batch_op.create_index(batch_op.f('ix_splits_value'), ['value'], unique=False)
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_splits_value'))
        batch_op.create_index(batch_op.f('ix_splits_amount'), ['amount'], unique=False)
        batch_op.drop_column('value')

    # ### end Alembic commands ###
