"""removed scoring and betting tables

Revision ID: a90a132e5a89
Revises: d189d6854218
Create Date: 2026-05-05 20:22:55.010143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90a132e5a89'
down_revision = 'd189d6854218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_betting_date'))

    op.drop_table('betting')
    with op.batch_alter_table('scoring', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoring_date'))

    op.drop_table('scoring')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scoring', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoring_date'), ['date'], unique=1)

    op.create_table('betting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('betting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_betting_date'), ['date'], unique=1)

    # ### end Alembic commands ###
