"""splits table

Revision ID: aac9548d365c
Revises: e6ab47907c82
Create Date: 2026-04-30 19:59:46.894148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac9548d365c'
down_revision = 'e6ab47907c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_splits_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_splits_layout'), ['layout'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_splits_layout'))
        batch_op.drop_index(batch_op.f('ix_splits_amount'))

    op.drop_table('splits')
    # ### end Alembic commands ###
