"""added scoring table

Revision ID: e35b514c2a00
Revises: 9437a5ee5b73
Create Date: 2026-05-03 14:42:10.390817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35b514c2a00'
down_revision = '9437a5ee5b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scoring', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoring_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scoring', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoring_date'))

    op.drop_table('scoring')
    # ### end Alembic commands ###
