"""rename table

Revision ID: e6ab47907c82
Revises: 931afa033f4f
Create Date: 2026-04-30 19:20:28.436355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ab47907c82'
down_revision = '931afa033f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('betting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_betting_date'), ['date'], unique=True)

    with op.batch_alter_table('betting_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_betting_page_date'))

    op.drop_table('betting_page')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betting_page',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('betting_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_betting_page_date'), ['date'], unique=1)

    with op.batch_alter_table('betting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_betting_date'))

    op.drop_table('betting')
    # ### end Alembic commands ###
